// "use client";

// import { useState } from "react";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import Navbar from "./navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [state, setState] = useState(0);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar />
        <h1>Layout: {state}</h1>
        <button
          className="px-6 py-2 bg-blue-800 text-white rounded-sm"
          onClick={() => {
            setState(state + 1);
          }}
        >
          Klik
        </button> */}

        {children}
      </body>
    </html>
  );
}
